theme: jekyll-theme-minimal

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# see https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
